//
//  Quotes.swift
//  Quotes Watch App
//
//  Created by itkhld on 10.01.2025.
//

import Foundation

let quotes = [
    "\"Your potential is endless.\"",
    "\"The future is yours.\"",
    "\"Take the leap.\"",
    "\"Stay inspired.\"",
    "\"Change is good.\"",
    "\"Success takes time.\"",
    "\"Follow your dreams.\"",
    "\"The world is yours.\"",
    "\"Make it happen today.\"",
    "\"One step at a time.\"",
    "\"Love yourself.\"",
    "\"No limits, only possibilities.\"",
    "\"Success is a journey.\"",
    "\"Keep chasing greatness.\"",
    "\"Stay calm and carry on.\"",
    "\"Be unstoppable.\"",
    "\"Progress, not perfection.\"",
    "\"Be proud of how far you’ve come.\"",
    "\"Your time is now.\"",
    "\"Stay hungry.\"",
    "\"Embrace the challenge.\"",
    "\"Do more, be more.\"",
    "\"Make the most of every moment.\"",
    "\"Don’t quit.\"",
    "\"Dare to dream.\"",
    "\"The best is yet to come.\"",
    "\"Today is a new chance.\"",
    "\"Great things take time.\"",
    "\"Let your light shine.\"",
    "\"Dream without fear.\"",
    "\"Do more, worry less.\"",
    "\"Take the risk.\"",
    "\"Live in the moment.\"",
    "\"Make it count.\"",
    "\"Be unstoppable.\"",
    "\"You are capable.\"",
    "\"Push your limits.\"",
    "\"Focus on today.\"",
    "\"Stay strong.\"",
    "\"Be the change.\"",
    "\"Life is short.\"",
    "\"Chase the dream.\"",
    "\"Never look back.\"",
    "\"Create your own path.\"",
    "\"Live with intention.\"",
    "\"Work smarter.\"",
    "\"Believe and achieve.\"",
    "\"Stay hungry, stay foolish.\"",
    "\"Success is earned.\"",
    "\"Progress over perfection.\"",
    "\"Trust the journey.\"",
    "\"The best is yet to come.\"",
    "\"Believe in yourself.\"",
    "\"Rise and shine.\"",
    "\"Keep moving forward.\"",
    "\"Act with purpose.\"",
    "\"Chase your goals.\"",
    "\"Be limitless.\"",
    "\"Push yourself.\"",
    "\"Stay focused.\"",
    "\"Dream bigger.\"",
    "\"Make every day count.\"",
    "\"Do what you love.\"",
    "\"Keep evolving.\"",
    "\"Never stop growing.\"",
    "\"Success starts with you.\"",
    "\"Be yourself.\"",
    "\"Stay authentic.\"",
    "\"Small steps lead to big changes.\"",
    "\"Make your dreams happen.\"",
    "\"Never give up.\"",
    "\"Create your success.\"",
    "\"Take action today.\"",
    "\"Life is a gift.\"",
    "\"Keep pushing forward.\"",
    "\"Live with passion.\"",
    "\"Don’t look back.\"",
    "\"Take the leap.\"",
    "\"Stay grateful.\"",
    "\"Every day is a chance.\"",
    "\"Take one step at a time.\"",
    "\"Make it happen.\"",
    "\"Find your strength.\"",
    "\"Live without limits.\"",
    "\"Challenge yourself.\"",
    "\"Make today great.\"",
    "\"Stay motivated.\"",
    "\"Trust yourself.\"",
    "\"Follow your heart.\"",
    "\"The future is bright.\"",
    "\"You are enough.\"",
    "\"Choose joy.\"",
    "\"Make it possible.\"",
    "\"Let it go.\"",
    "\"Keep learning.\"",
    "\"You can do it.\"",
    "\"The time is now.\"",
    "\"Live fully.\"",
    "\"Stay optimistic.\"",
    "\"Be the best you.\"",
    "\"Your only limit is you.\"",
    "\"Believe in your dreams.\"",
    "\"You have what it takes.\"",
    "\"Stay positive.\"",
    "\"Keep going.\"",
    "\"Focus on what matters.\"",
    "\"Dream it, do it.\"",
    "\"Stay true to yourself.\"",
    "\"Keep going, never stop.\"",
    "\"You’re stronger than you think.\"",
    "\"Your dreams are valid.\"",
    "\"Make it work.\"",
    "\"You’re on the right path.\"",
    "\"Live in the moment.\"",
    "\"Take it one day at a time.\"",
    "\"Success is a choice.\"",
    "\"Follow your passion.\"",
    "\"Keep believing.\"",
    "\"Stay the course.\"",
    "\"Make the most of today.\"",
    "\"Everything starts with you.\"",
    "\"The best is yet to come.\"",
    "\"Start where you are.\"",
    "\"You’re capable of more.\"",
    "\"Create your own path.\"",
    "\"Don’t stop now.\"",
    "\"Focus on the good.\"",
    "\"Enjoy the journey.\"",
    "\"Make the change.\"",
    "\"Success is within reach.\"",
    "\"Your time is now.\"",
    "\"Stay committed.\"",
    "\"Keep your head up.\"",
    "\"Live without regrets.\"",
    "\"Keep your goals in sight.\"",
    "\"Life is what you make it.\"",
    "\"The world is waiting.\"",
    "\"You have the power.\"",
    "\"Focus on your goals.\"",
    "\"Live the life you love.\"",
    "\"Be your own hero.\"",
    "\"You control your future.\"",
    "\"Make it count.\"",
    "\"Never stop believing.\"",
    "\"Start now.\"",
    "\"You’re doing great.\"",
    "\"Success is earned daily.\"",
    "\"Your dreams matter.\"",
    "\"You’re destined for greatness.\"",
    "\"Believe in today.\"",
    "\"Rise above.\"",
    "\"Keep striving.\"",
    "\"Stay curious.\"",
    "\"Believe it’s possible.\"",
    "\"Dream big, start small.\"",
    "\"Keep your eyes on the prize.\"",
    "\"Make your mark.\"",
    "\"Be kind to yourself.\"",
    "\"Stay hungry, stay humble.\"",
    "\"Do it with passion.\"",
    "\"Keep chasing your dreams.\"",
    "\"Believe in the journey.\"",
    "\"The sky’s the limit.\"",
    "\"You are unstoppable.\"",
    "\"Everything is possible.\"",
    "\"Make every moment count.\"",
    "\"Keep it moving.\"",
    "\"Take chances.\"",
    "\"It’s your time.\"",
    "\"No limits, just possibilities.\"",
    "\"Dream it, live it.\"",
    "\"Stay consistent.\"",
    "\"Trust the process.\"",
    "\"You are capable of greatness.\"",
    "\"Change is progress.\"",
    "\"Never settle.\"",
    "\"Stay determined.\"",
    "\"Do what you love.\"",
    "\"You are your only limit.\"",
    "\"Don’t wait for the perfect moment.\"",
    "\"You make your own path.\"",
    "\"Happiness depends on ourselves.\"",
    "\"The best way to predict the future is to create it.\"",
    "\"Believe you can and you're halfway there.\"",
    "\"Life is what happens when you're busy making other plans.\"",
    "\"Success is not final, failure is not fatal: It is the courage to continue that counts.\"",
    "\"The only way to do great work is to love what you do.\"",
    "\"Success is not the key to happiness. Happiness is the key to success.\"",
    "\"Do not go where the path may lead, go instead where there is no path and leave a trail.\"",
    "\"Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.\"",
    "\"It does not matter how slowly you go as long as you do not stop.\"",
    "\"You are never too old to set another goal or to dream a new dream.\"",
    "\"Keep your face always toward the sunshine—and shadows will fall behind you.\"",
    "\"Success usually comes to those who are too busy to be looking for it.\"",
    "\"The harder you work for something, the greater you’ll feel when you achieve it.\"",
    "\"Don’t watch the clock; do what it does. Keep going.\"",
    "\"The future belongs to those who believe in the beauty of their dreams.\"",
    "\"In the middle of every difficulty lies opportunity.\"",
    "\"What lies behind us and what lies before us are tiny matters compared to what lies within us.\"",
    "\"You don’t have to be great to start, but you have to start to be great.\"",
    "\"The best revenge is massive success.\"",
    "\"The only limit to our realization of tomorrow is our doubts of today.\"",
    "\"Success is not in what you have, but who you are.\"",
    "\"Our lives are what our thoughts make it.\"",
    "\"What we think, we become.\"",
    "\"Act as if what you do makes a difference. It does.\"",
    "\"Keep your eyes on the stars, and your feet on the ground.\"",
    "\"The only way to achieve the impossible is to believe it is possible.\"",
    "\"Everything you can imagine is real.\"",
    "\"You only live once, but if you do it right, once is enough.\"",
    "\"It always seems impossible until it’s done.\"",
    "\"Don’t be afraid to fail.\"",
    "\"Stay positive, work hard.\"",
    "\"You are your biggest supporter.\"",
    "\"Life is a beautiful struggle.\"",
    "\"Keep your focus.\"",
    "\"Start strong, finish stronger.\"",
    "\"Keep working, stay humble.\"",
    "\"Make things happen.\"",
    "\"Success is a habit.\"",
    "\"Follow your heart and trust your instincts.\"",
    "\"The best time is now.\"",
    "\"Be bold, be brave.\"",
    "\"No excuses, just results.\"",
    "\"Start with a plan, finish with results.\"",
    "\"You can do hard things.\"",
    "\"Live with no regrets.\"",
    "\"Stay consistent, stay focused.\"",
    "\"Every step counts.\"",
    "\"Take pride in your journey.\"",
    "\"Your potential is limitless.\"",
    "\"Keep the faith.\"",
    "\"Stay inspired.\"",
    "\"Take control of your future.\"",
    "\"Small steps lead to big results.\"",
    "\"Success begins with a decision.\"",
    "\"Stay positive, always.\"",
    "\"Keep your dream alive.\"",
    "\"The power is in your hands.\"",
    "\"Stay motivated, stay driven.\"",
    "\"Hard work pays off.\"",
    "\"Create the life you deserve.\"",
    "\"Keep fighting for your dreams.\"",
    "\"Success is a mindset.\"",
    "\"Believe in your path.\"",
    "\"The journey is the reward.\"",
    "\"Be your own inspiration.\"",
    "\"Life is about making an impact.\"",
    "\"You can achieve anything.\"",
    "\"Chase success.\"",
    "\"Keep climbing.\"",
    "\"Stay driven, stay focused.\"",
    "\"Don’t give up now.\"",
    "\"You’re on the right track.\"",
    "\"The time for change is now.\"",
    "\"Live with no limits.\"",
    "\"You are worthy of success.\"",
    "\"Progress over perfection.\"",
    "\"Live boldly.\"",
    "\"Do what you can, with what you have, where you are.\"",
    "\"Don’t wait. The time will never be just right.\"",
    "\"You must be the change you wish to see in the world.\"",
    "\"Your time is limited, so don’t waste it living someone else’s life.\"",
    "\"In three words I can sum up everything I’ve learned about life: It goes on.\"",
    "\"Life isn’t measured by the breaths you take, but by the moments that take your breath away.\"",
    "\"There are no secrets to success. It is the result of preparation, hard work, and learning from failure.\"",
    "\"Success is walking from failure to failure with no loss of enthusiasm.\"",
    "\"To live is the rarest thing in the world. Most people exist, that is all.\"",
    "\"I have not failed. I’ve just found 10,000 ways that won’t work.\"",
    "\"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.\"",
    "\"Be the change that you wish to see in the world.\"",
    "\"Success is how high you bounce when you hit bottom.\"",
    "\"It’s not whether you get knocked down, it’s whether you get up.\"",
    "\"The best way to get started is to quit talking and begin doing.\"",
    "\"You can’t go back and change the beginning, but you can start where you are and change the ending.\"",
    "\"There is no greater agony than bearing an untold story inside you.\"",
    "\"Life isn’t about finding yourself. Life is about creating yourself.\"",
    "\"The only impossible journey is the one you never begin.\"",
    "\"You just can’t beat the person who never gives up.\"",
    "\"The greatest glory in living lies not in never falling, but in rising every time we fall.\"",
    "\"The way to get started is to quit talking and begin doing.\"",
    "\"Life is either a daring adventure or nothing at all.\"",
    "\"Life is short, and it is up to you to make it sweet.\"",
    "\"Success is not the key to happiness. Happiness is the key to success.\"",
    "\"The only limit to our realization of tomorrow is our doubts of today.\"",
    "\"In the end, it's not the years in your life that count, it's the life in your years.\"",
    "\"Success is not final, failure is not fatal: It is the courage to continue that counts.\"",
    "\"You can never plan the future by the past.\"",
    "\"It always seems impossible until it’s done.\"",
    "\"Do not go where the path may lead, go instead where there is no path and leave a trail.\"",
    "\"We do not remember days, we remember moments.\"",
    "\"Doubt kills more dreams than failure ever will.\"",
    "\"Your time is limited, so don’t waste it living someone else’s life.\"",
    "\"Don't judge each day by the harvest you reap but by the seeds that you plant.\"",
    "\"Success is not the key to happiness. Happiness is the key to success.\"",
    "\"The only way to achieve the impossible is to believe it is possible.\"",
    "\"Everything you can imagine is real.\"",
    "\"You only live once, but if you do it right, once is enough.\"",
    "\"It always seems impossible until it’s done.\"",
    "\"Do what you can, with what you have, where you are.\"",
    "\"Don’t wait. The time will never be just right.\"",
    "\"You must be the change you wish to see in the world.\"",
    "\"Your time is limited, so don’t waste it living someone else’s life.\"",
    "\"In three words I can sum up everything I’ve learned about life: It goes on.\"",
    "\"Life isn’t measured by the breaths you take, but by the moments that take your breath away.\"",
    "\"Do it now.\"",
    "\"Live your dreams.\"",
    "\"Keep going.\"",
    "\"Stay humble.\"",
    "\"Make it happen.\"",
    "\"Dream big.\"",
    "\"Be kind.\"",
    "\"Create your future.\"",
    "\"Seize the day.\"",
    "\"Make today count.\"",
    "\"Choose happiness.\"",
    "\"Never stop learning.\"",
    "\"Be fearless.\"",
    "\"Stay positive.\"",
    "\"Embrace change.\"",
    "\"You are enough.\"",
    "\"Believe in yourself.\"",
    "\"Stay strong.\"",
    "\"Keep moving forward.\"",
    "\"Be the light.\"",
    "\"Live with purpose.\"",
    "\"Stay focused.\"",
    "\"Love life.\"",
    "\"Start today.\"",
    "\"Be brave.\"",
    "\"Rise above.\"",
    "\"Let it go.\"",
    "\"Stay true.\"",
    "\"Act now.\"",
    "\"Stay curious.\"",
    "\"Be bold.\"",
    "\"Create joy.\"",
    "\"Keep smiling.\"",
    "\"Learn from failure.\"",
    "\"Live authentically.\"",
    "\"Keep it simple.\"",
    "\"Find peace.\"",
    "\"Be the change.\"",
    "\"Focus on the good.\"",
    "\"Let it be.\"",
    "\"Be happy.\"",
    "\"Trust the process.\"",
    "\"Work hard.\"",
    "\"Make a difference.\"",
    "\"Choose love.\"",
    "\"Stay grateful.\"",
    "\"Enjoy the journey.\"",
    "\"Live fully.\"",
    "\"Find balance.\"",
    "\"Give your best.\"",
    "\"Stay motivated.\"",
    "\"Do what you love.\"",
    "\"Think positive.\"",
    "\"You got this.\"",
    "\"Follow your heart.\"",
    "\"Keep learning.\"",
    "\"Be present.\"",
    "\"Trust yourself.\"",
    "\"Be unique.\"",
    "\"The best is yet to come.\"",
    "\"Stay humble, stay kind.\"",
    "\"You are stronger than you think.\"",
    "\"Success is a choice.\"",
    "\"Be your own hero.\"",
    "\"Life is a gift.\"",
    "\"Every day is a new beginning.\"",
    "\"Good things take time.\"",
    "\"Start small, dream big.\"",
    "\"Believe in your dreams.\"",
    "\"Make it count.\"",
    "\"Your vibe attracts your tribe.\"",
    "\"Small steps, big dreams.\"",
    "\"Don’t stop now.\"",
    "\"Go after your dreams.\"",
    "\"Success starts with you.\"",
    "\"Make your mark.\"",
    "\"Find joy in the journey.\"",
    "\"Chase your passion.\"",
    "\"Don’t settle.\"",
    "\"Live with passion.\"",
    "\"Be your best self.\"",
    "\"Do more of what makes you happy.\"",
    "\"Success is earned.\"",
    "\"Think big, start small.\"",
    "\"Create your own luck.\"",
    "\"The way to get started is to quit talking and begin doing.\"",
    "\"The secret of getting ahead is getting started.\"",
    "\"Nothing is impossible, the word itself says ‘I’m possible!’\"",
    "\"It’s never too late to be what you might have been.\"",
    "\"It’s not the years in your life that count. It’s the life in your years.\"",
    "\"Success doesn’t just find you. You have to go out and get it.\"",
    "\"Everything you’ve ever wanted is on the other side of fear.\"",
    "\"Opportunities don’t happen, you create them.\"",
    "\"The hard days are what make you stronger.\"",
    "\"Don’t stop when you’re tired. Stop when you’re done.\"",
    "\"Wake up with determination. Go to bed with satisfaction.\"",
    "\"Do something today that your future self will thank you for.\"",
    "\"Little things make big days.\"",
    "\"It’s going to be hard, but hard does not mean impossible.\"",
    "\"Don’t wait for opportunity. Create it.\"",
    "\"Sometimes we’re tested not to show our weaknesses, but to discover our strengths.\"",
    "\"The key to success is to focus on goals, not obstacles.\"",
    "\"Dream it. Wish it. Do it.\"",
    "\"Success doesn’t just find you. You have to go out and get it.\"",
    "\"The best way to predict the future is to create it.\"",
    "\"Hardships often prepare ordinary people for an extraordinary destiny.\"",
    "\"Believe you can and you’re halfway there.\"",
    "\"Success is the sum of small efforts, repeated day in and day out.\"",
    "\"Don’t watch the clock; do what it does. Keep going.\"",
    "\"You are never too old to set another goal or to dream a new dream.\"",
    "\"The future belongs to those who believe in the beauty of their dreams.\"",
    "\"Life is what happens when you’re busy making other plans.\"",
    "\"If you want to achieve greatness stop asking for permission.\"",
    "\"Success is not how high you have climbed, but how you make a positive difference to the world.\"",
    "\"In the end, we will remember not the words of our enemies, but the silence of our friends.\"",
    "\"The best time to plant a tree was 20 years ago. The second best time is now.\"",
    "\"Whether you think you can or you think you can’t, you’re right.\"",
    "\"Stay determined.\""
]

